### ISSUE TITLE
Running the test command from CI lauches a watch

### ISSUE THREAD

**Issue by shhyou** [rfindler/esterel#8]
I tried to test my local installation using the command from the CI workflow:
https://github.com/rfindler/esterel/blob/e4a246002d7775ae7b2c9d2c3d0820ca501e3982/.github/workflows/ci.yaml#L30-L31
and yet it launches a watch (a GUI app).

**Comment by rfindler** [comment]
I've fixed the watch to not do that [(pushed here)](https://github.com/rfindler/esterel/commit/4cbac4841532a960fe580042e042880843c9bd47) but there are also problems at the moment with the rhombus version of Esterel. I think those fixes are being worked but maybe just enough could be pushed to main to avoid errors for now, if that would be helpful to you?
